<% header(name + ' 0.9.1 Release Notes') %>

<p><% name %> version 0.9.1 released on 04/23/06</p>

<a name="NewFeatures"></a><h2>New Features</h2>
<ul>
	<li>The <code>SQLObjectStore</code> class has got a new method
	<code>refreshObject()</code>.</li>
</ul>

<a name="Bugfixes"></a><h2>Bugfixes</h2>
<ul>
	<li>You now get a useful error message when the class ids in the database
	don't match the class names in the model.</li>
	<li>A bug with passing the <code>database</code> argument and a couple
	of other bugs have been fixed.</li>
</ul>

<% footer() %>