<% header(name + ' 0.2.1 Release Notes') %>

<p>Webware for Python 0.7 beta 1</p>

<a name="Changes"></a><h2>Changes</h2>
<ul>
	<li>Version 0.2.1 was released on 12/10/2001.</li>
	<li>In certain situations, MiddleKit could store an invalid object
reference in the SQL database. This would cause a warning when
retrieving the object and a disconnect between the source and target
objects.</li>
	<li>MiddleKit didn't properly support the 'Package' setting in many cases.</li>
</ul>

<% footer() %>