<% header(name + ' ' + versionString + ' Release Notes') %>

<p><% name %> version <% versionString %> released on <% releaseDate %></p>

<a name="Bugfixes"></a><h2>Bugfixes</h2>
<ul>
	<li>Fixes in MKBrowser: Memorizing recent models did not work.
	The wrong directory was added to the sys.path (bug 1443141).</li>
	<li>Some more bugs have been fixed in MiddleKit and the Video tutorial.</li>
</ul>

<% footer() %>