<% header(name + ' 0.7 Release Notes') %>

<p>Webware for Python 0.7</p>

<a name="General"></a><h2>General</h2>
<ul>
	<li>CSVs with embedded commas, quotes and newlines (as can be produced by popular programs such as MySQL and Excel) are now properly read. (Added CSVParser.py which is the new parsing guts for DataTable. You are still more likely to use DataTable for reading CSVs as it has more power and convenience.)</li>
</ul>

<% footer() %>