<% header(name + ' 0.4 Release Notes') %>

<p>Webware for Python 0.4</p>

<a name="Changes"></a><h2>Changes</h2>
<ul>
	<li>Version 0.4 was released on 8/12/2000.</li>
	<li>Added documentation for the first time.</li>
	<li>Added NamedValueAccess which was formally called KeyValueAccess and located in MiddleKit.</li>
	<li>Added DataTable.</li>
	<li>See the <a href="UsersGuide.html">User's Guide</a> for details.</li>
</ul>

<% footer() %>