<% header(name + " User's Guide") %>

<p class="right"><% name %> version <% versionString %></p>

<!-- contents -->


<a name="Synopsis"></a><h2>Synopsis</h2>

<p>MiscUtils provides support classes and functions to Webware that aren't necessarily web-related and that don't fit into one of the other frameworks. There is plenty of useful reusable code here.</p>


<a name="Feedback"></a><h2>Feedback</h2>

<p>You can e-mail <a href="mailto:webware-discuss@lists.sourceforge.net">webware-discuss@lists.sourceforge.net</a> to give feedback, discuss features and get help using MiscUtils.</p>


<a name="Classes"></a><h2>Classes</h2>

<p>There are several interesting modules contained in MiscUtils, each of which contains it's own documentation embedded in the source.</p>

<p>Please browse through the list of <a href="Source/FileList.html">modules</a> and <a href="Source/ClassList.html">classes</a> in MiscUtils.</p>


<a name="KnownBugs"></a><h2>Known Bugs</h2>

<p>Known bugs and future work in general is documented with each class.</p>


<a name="Credit"></a><h2>Credit</h2>

<p>Author: Chuck Esterbrook<br>
except unittest by Steve Purcell</p>

<% footer() %>