<% header(name + ' 0.3 Release Notes') %>

<p>Webware for Python 0.4</p>

<a name="ReleaseNotes"></a><h2>Release Notes</h2>
<ul>
	<li>Version 0.3 was released on 9/28/2000.</li>
	<li>Version 0.3 represents a stabilization of the basic syntax and raw capabilities of the PSP module for WebKit.  All of the basic functionality is there and works as expected.  The only major addition for this release is a new, optional syntax for handling Python blocks that need to include straight HTML (curly braces).</li>
</ul>

<% footer() %>