<% header(name + ' 0.4 Release Notes') %>

<p>Webware for Python 0.5</p>

<a name="ReleaseNotes"></a><h2>Release Notes</h2>

<ul>
	<li>Version 0.4 was released on 3/1/2001.</li>
	<li>New Block syntax, Braces, was added.  It was present in the Webware 0.4 release, but undocumented as it was experimental.  It has received a fair amount of use and is now ready for prime time.  The use of braces for PSP syntax removes the need to worry about whitespace indentation in the Python code you put in your PSP pages.  Instead, you use braces ( { and }) to signify blocks, which can span script blocks.  This will probably be the most effective means of coding in PSP pages.  In order to use this type of indentation, you need to specify it at the top of your PSP page.  See the <a href="UsersGuide.html">UsersGuide</a> for more information.</li>
	<li>You can now inherit from multiple base classes in a PSP using: <code>&lt;%@ page extends="Base1,Base2,Base3"%&gt;</code></li>
	<li>Bugfix: If the path of your PSP included something like a "~" it would break. [Geoff T]</li>
	<li>Bugfix: Removed the try/except block around the import of the parent class of PSP pages. This ate up error messages when the parent couldn't be imported. [Jay L]</li>
	<li>Minor doc and example refinements. [Jay L, Geoff T]</li>
</ul>

<% footer() %>