<% header(name + ' 0.2.2 Release Notes') %>

<p>Webware for Python</p>

<a name="Changes"></a><h2>Changes</h2>
<ul>
	<li> Version 0.2.2 was released on 6/13/2001.
	<li> CGIWrapper's exception handling no longer fails on non-posix platforms such as Windows ME. Previously, it was trying to get too many OS values such as getegid(). Now it only gets the ones that are available.</li>
	<li> sys.path is dealt with better. A <b>''</b> always appears at the front, and the <b>'..'</b> that was previously installed (in the event that Webware modules couldn't be found) is now passed through os.path.abspath().</li>
</ul>

<% footer() %>