<% header(name + ' 0.7 Release Notes') %>

<p>Webware for Python 0.7</p>

<a name="Changes"></a><h2>Changes</h2>
<ul>
	<li>New versioning strategy: all Webware components will now have their version numbers updated in lock-step.</li>
</ul>

<a name="Earlier"></a><h2>Earlier Changes</h2>
<ul>
    <li><p>2000-04-17:</p>
    <ul>
	<li>Fixed a fairly serious bug in HTMLForException() where HTMLEncode() wasn't effectively used in many cases. That resulted in bizarre/wrong looking exception reports.</li>
	<li>Provided a better, but still incomplete ver of the docs.</li>
	<li>Turned WebUtils into a package.</li>
    </ul></li>
</ul>

<% footer() %>