<% header('Webware Copyright et al', 'titlebar') %>

<h2>The Gist</h2>

<p>Webware for Python is open source, but there is no requirement that products developed with or derivative to Webware become open source.</p>

<p>Webware for Python is copyrighted, but you can freely use and copy it as long as you don't change or remove this copyright notice. The license is a clone of the original <a href="http://www.opensource.org/licenses/">OSI-approved</a> Python license.</p>

<p>There is no warranty of any kind. Use at your own risk.</p>

<p>Read this entire document for complete, legal details.</p>


<h2>Copyright</h2>

<p>Copyright &copy; 1999-2001 by Chuck Esterbrook.
<br>All Rights Reserved</p>

<h2>License</h2>

<p>Permission to use, copy, modify, and distribute this software and its documentation for any purpose and without fee is hereby granted, provided that the above copyright notice appear in all copies and that both that copyright notice and this permission notice appear in supporting documentation, and that the names of the authors not be used in advertising or publicity pertaining to distribution of the software without specific, written prior permission.</p>

<h2>Disclaimer</h2>

<p>THE AUTHORS DISCLAIM ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.</p>

<h2>Trademarks</h2>

<p>All trademarks referred to in the source code, documentation, sample files or otherwise, are reserved by their respective owners.</p>

<% footer() %>