<% header('Webware Documentation', 'titlebar', 'DocIndex.css') %>

<p class="center"><b>Version <% versionString %><br><% releaseDate %></b></p>

<table align="center" cellspacing="4" cellpadding="4" border="0" style="border: 2px solid #002352">
<tr style="background-color:#E8E8FF">
<td valign="top" nowrap>
	<ul>
		<li><a href="Overview.html" class="BigLink">Overview</a>
		<br>(start here)</li>
		<li><a href="ComponentIndex.html" class="BigLink">Component Index</a>
		<br>(overview and pointers to all components)</li>
		<li><a href="Copyright.html" class="BigLink">Copyright et al</a>
		<br>(open source copyright, license and disclaimer)</li>
	</ul>
</td>
<td valign="top">
	<ul>
		<li><a href="RelNotes.html" class="BigLink">Release Notes</a>
		<br>(release notes for Webware)</li>
		<li><a href="StyleGuidelines.html" class="BigLink">Style Guidelines</a>
		<br>(guidelines for Webware developers)</li>
		<li><a href="ReleaseProcedures.html" class="BigLink">Release Procedures</a>
		<br>(how to cut a Webware release)</li>
	</ul>
</td>
</tr>
<tr style="background-color:#F0F0F0">
<td valign="top">
	<ul>
		<li><a href="http://www.webwareforpython.org" class="BigLink">Webware</a>
		<br>(the Webware for Python home page)</li>
		<li><a href="http://wiki.w4py.org" class="BigLink">Webware Wiki</a>
		<br>(the Webware project's Wiki site)</li>
		<li><a href="http://sourceforge.net/projects/webware/" class="BigLink">Webware@SourceForge</a>
		<br>(the Webware project page at SourceForge)</li>
<!--
		<li><a href="http://lists.sourceforge.net/mailman/listinfo/webware-discuss" class="BigLink">webware-discuss</a>
		<br>(discussion list home page)</li>
		<li><a href="http://lists.sourceforge.net/mailman/listinfo/webware-announce" class="BigLink">webware-announce</a>
		<br>(announce list home page)</li>
-->
		<li><a href="http://wiki.w4py.org/webwarehosting.html" class="BigLink">Webware Hosting</a>
		<br>(find a host for your Webware app)</li>
	</ul>
</td>
<td valign="top">
	<ul>
		<li><a href="http://www.python.org" class="BigLink">Python</a>
		<br>(Python home page)</li>
		<li><a href="http://wiki.python.org/moin/" class="BigLink">Python Wiki</a>
		<br>(the PythonInfo Wiki)</li>
		<li><a href="http://www.python.org/psf/" class="BigLink">Python Software Foundation</a>
		<br>(the home page for the PSF)</li>
<!--
		<li><a href="news:comp.lang.python" class="BigLink">comp.lang.python newsgroup</a>
		<br>(Python discussions newsgroup)</li>
		<li><a href="news:comp.lang.python.announce" class="BigLink">comp.lang.python.announce</a>
		<br>(Python announcements forum)</li>
-->
		<li><a href="http://www.python.org/cgi-bin/moinmoin/PythonHosting" class="BigLink">Python-friendly ISPs</a>
		<br>(find a host for your Python app)</li>
	</ul>
</td>
</tr>
</table>

<% footer() %>