<% header(name + ' 0.2 Release Notes') %>

<a name="ReleaseNotes"></a><h2>Release Notes</h2>

<ul>
	<li>Version 0.2 was released on 5/12/2000.</li>
	<li> There is an improved <a href="../WebKit/Docs/WebKit.html">WebKit</a> <a href="../WebKit/Docs/RelNotes-0.2.html">0.2</a> with new features, refinements and bugfixes.</li>
	<li> There is an improved <a href="../CGIWrapper/Docs/CGIWrapper.html">CGIWrapper</a> <a href="../CGIWrapper/Docs/CGIWrapper.html#ReleaseNotes">0.2</a> with new features, refinements and bugfixes.</li>
	<li> The project is now partially hosted on <a href="http://sourceforge.net">SourceForge</a> at <a href="http://webware.sourceforge.net">http://webware.sourceforge.net</a>, although the CVS repository is not yet set up.</li>
	<li> As usual, the bulk of the documentation and release notes is with the components themselves. Please use the links above.</li>
</ul>

<% footer() %>