<% header(name + ' 0.4 Release Notes') %>

<a name="ReleaseNotes"></a><h2>Release Notes</h2>

<ul>
	<li>Version 0.4 was released on 9/28/2000.</li>
	<li>Webware has found use in the real world resulting in plenty of excellent feedback, refinements and bugfixes.</li>
	<li>There is a new <b>install.py</b> script in the main Webware directory that is required to be run.</li>
	<li>The install script, among other things, generates HTML class hierarchies, file summaries and syntax-highlighted source as part of the documentation.</li>
	<li>A comprehensive installation guide for WebKit.</li>
	<li>More integration with other web technologies like mod_python, PyWX/AOLserver, etc.</li>
	<li>Better behavior on Windows with no known Windows problems.</li>
	<li><a href="../MiscUtils/Documentation/MiscUtils.html">MiscUtils</a> has been expanded on, and documented for the first time.</li>
	<li>There is an improved <a href="../WebKit/Documentation/WebKit.html">WebKit</a> <a href="../WebKit/Documentation/RelNotes-0.4.html">0.4</a>.</li>
	<li>There is an improved <a href="../PSP/Documentation/PSP.html">PSP</a> <a href="../PSP/Documentation/RelNotes-0.2.html">0.2</a>.</li>
	<li>As usual, the bulk of the documentation and release notes is with the components themselves. Please use the links above.</li>
</ul>

<% footer() %>