<% header(name + ' 0.9.1 Release Notes') %>

<p><% name %> version 0.9.1 released on 04/23/06</p>

<ul>
	<li>This release of Webware for Python includes a few fixes and
	improvements of the WebKit, MiddleKit and KidKit plug-ins (see
	the respective release notes).</li>
	<li>The <span class="filename">MakeAppWorkDir.py</span> script
	now allows to be run on an existing directory. This will create
	all missing files and directories, and set access permissions
	accordingly (requested by Andreas Poisel).</li>
	<li>Compatibility with Python&nbsp;2.5 has been factored in,
	although this has not yet been throughly tested (and a stable
	version is not yet available anyway).</li>
</ul>

<% footer() %>