<% header(name + ' 0.3 Release Notes') %>

<a name="ReleaseNotes"></a><h2>Release Notes</h2>

<ul>
	<li>Version 0.3 was released on 6/6/2000.</li>
	<li>There is an improved <a href="../WebKit/Docs/WebKit.html">WebKit</a> <a href="../WebKit/Docs/RelNotes-0.3.html">0.3</a> with new features, refinements and bugfixes.</li>
	<li>There is a new <a href="../PSP/Docs/PSP.html">PSP</a> component (aka Python Server Pages) which is a WebKit <a href="../WebKit/Docs/UsersGuide.html#plug-ins">plug-in</a> that enables you to create server pages that freely mix HTML and Python in the same fashion as other popular server technologies such as ASP, PHP and JSP.</li>
	<li>The project is now fully hosted on <a href="http://sourceforge.net">SourceForge</a> at <a href="http://webware.sourceforge.net">http://webware.sourceforge.net</a> including the CVS source code repository. You can anonymously checkout a snapshot of the repository if you want the latest, in-development version.</li>
	<li>Webware is now friendlier to Windows including both code and documentation. We now have developers using both Windows and UNIX/Linux.</li>
	<li>As usual, the bulk of the documentation and release notes is with the components themselves. Please use the links above.</li>
</ul>

<% footer() %>
