<% header(name + ' 0.4.1 Release Notes') %>

<a name="ReleaseNotes"></a><h2>Release Notes</h2>

<ul>
	<li>Version 0.4.1 was released on 10/5/2000.</li>
	<li>We're officially supporting both Python 1.5.2 and 2.0b2.</li>
	<li>Some minor fixes to <a href="../WebKit/Docs/WebKit.html">WebKit</a> as described in its <a href="../WebKit/Docs/RelNotes-0.4.1.html">release notes</a>.</li>
</ul>

<% footer() %>