<% header(name + ' 0.6 Release Notes') %>

<p>Version 0.6 was released on 12/2/2001.</p>

<p>This release does not introduce any new components/packages, but instead adds new features and fixes bugs in existing packages.</p>

<p>Please see the <a href="ComponentIndex.html">Component Index</a> for access to the documentation for each component.</p>

<p>Also, visit the <a href="http://webware.sourceforge.net/">Webware home page</a> and <a href="http://webware.sourceforge.net/Wiki/">Wiki</a> for further information about Webware.</p>

<% footer() %>